### PR TITLE
add android kernel worktree

### PR DESCRIPTION
**Pull request by isaac2-lee**
#### path
├── third-party
│   ├── android-kernel (android12-5.10 kernel)
│   ├── gki-build (kernel build configs) 

#### build-command
gki-build> BUILD_CONFIG=../android-kernel/build.config.gki.aarch64 build/build.sh

### CODE REVIEW

**Comment by bitboom** [comment]
Please let me know upstream urls. And could you keep `gki-build` commit history too?

**Comment by isaac2-lee** [comment]
> Please let me know upstream urls. And could you keep `gki-build` commit history too?
source download reference: https://source.android.com/docs/setup/create/repo#init
```
repo init -u https://android.googlesource.com/kernel/manifest -b common-android12-5.10
```
in this repo, I can't find the root history about `/kernel`

In my opinion, each subdirectories(build, common, etc..) have a their own history and repo.
(i.e. https://android.googlesource.com/kernel/build)
anyway except kernel sources, there are many submodule for build.
That's why I merged and squashed it.

**Comment by isaac2-lee** [comment]
> > Please let me know upstream urls. And could you keep `gki-build` commit history too?
> > source download reference: https://source.android.com/docs/setup/create/repo#init
> 
I found it.

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <remote  name="aosp" fetch=".." review="https://android-review.googlesource.com/" />
  <default revision="master-kernel-build-2021" remote="aosp" sync-j="4" />

  <superproject name="kernel/superproject" remote="aosp" revision="common-android12-5.10" />

  <project path="build" name="kernel/build" />
  <project path="hikey-modules" name="kernel/hikey-modules" revision="android12-5.10" />
  <project path="common" name="kernel/common" revision="android12-5.10" />
  <project path="kernel/tests" name="kernel/tests" />
  <project path="kernel/configs" name="kernel/configs" />
  <project path="common-modules/virtual-device" name="kernel/common-modules/virtual-device" revision="android12-5.10" />
  <project path="prebuilts-master/clang/host/linux-x86" name="platform/prebuilts/clang/host/linux-x86" clone-depth="1" />
  <project path="prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8" name="platform/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8" clone-depth="1" />
  <project path="prebuilts/build-tools" name="platform/prebuilts/build-tools" clone-depth="1" />
  <project path="prebuilts/kernel-build-tools" name="kernel/prebuilts/build-tools" clone-depth="1" />
  <project path="tools/mkbootimg" name="platform/system/tools/mkbootimg" />
</manifest>
```

**Review by bitboom — APPROVED** [review]
It's okay for now. But i think we need to discuss more how to maintain `third-party/gki-build source` later.

**Pull request merged**
