### PR TITLE
Add HES app and use it together with modified TF-A

### PR DESCRIPTION
**Pull request by Havner**
This PR requires https://github.com/Samsung/islet-asset/pull/7 to be merged first.
This PR consists of 3 separate patches, please don't squash it when merging.

This PR changes the following:
- compiles the modified TF-A (from the before mentioned PR) with measured boot and HES over serial
- adds HES app from an external repo
- runs the HES app before FVP (with daemonize option)
- kills the HES app on SIGINT/SIGTERM and on FVP start (in case something went wrong)

### CODE REVIEW

**Comment by Havner** [comment]
Two tests failed due to lack of space on the device.
One seems like it requires re-initialization of the repository on CI as new submodule has been added.
All of this is outside of my power to fix at the moment.

**Comment by p-sawicki2** [comment]
@zpzigi754 @bitboom Could you help us resolve the issues related to failing tests on CI?

**Comment by bitboom** [comment]
> @zpzigi754 @bitboom Could you help us resolve the issues related to failing tests on CI?

Sure. @zpzigi754 have took a look about CI issues now. I will also support him.

**Comment by zpzigi754** [comment]
> @zpzigi754 @bitboom Could you help us resolve the issues related to failing tests on CI?

I am sorry for the late response. I was off on last Friday and yesterday was holiday in Korea. 

Regarding `realm-linux-booting` failure, it is a build time error. You would be able to reproduce the symptom with the latest ubuntu docker image by executing the below commands 
```
(inside docker)
./scripts/init_min.sh                                 // Install minimum dependency required for this test
./scripts/tests/realm-boot.sh                 // Build and run realm-linux booting test
```

Regarding `acs` and `tf-a-tests` failures, it is our maintenance issue. I've contacted a person in the Samsung's open source department to subscribe github's non-free service which can increase the limit of storage, yet the issue seems rather complex. The person said that github doesn't allow a single repository under organization to be changed to be non-free service (Changing all repositories under Samsung to non-free service would cost a lot). We might need to move our repository out of the organization (Samsung) for the non-free service, but the decision has not been made. I will let you know if any progress is made for this direction.

Another option would be removing unnecessary dependency as much as possible to leave a small storage footprint. https://github.com/Samsung/islet/pull/196 has  been working for this direction and I will finish it soon.

**Comment by zpzigi754** [comment]
> Two tests failed due to lack of space on the device. One seems like it requires re-initialization of the repository on CI as new submodule has been added. All of this is outside of my power to fix at the moment.

@Havner @p-sawicki2, I've fixed the ci issues in https://github.com/Samsung/islet/pull/196. Rebasing to the main branch will help to pass the tests.

**Comment by Havner** [comment]
I've rebased and pushed again but I expect the tests to fail anyway (hopefully with different reason) as the https://github.com/Samsung/islet-asset/pull/7 is not merged and it's required by this PR.

**Comment by Havner** [comment]
3 tests failing due to lack of mbedtls, which is pushed to islet-assets repo. So besides the fact the before-mentioned PR needs to be merged some re-initialization of the repository on CI is required? No idea exactly how this stuff works. mbedtls is added as a submodule here.

**Review by bitboom — APPROVED** [review]

**Comment by Havner** [comment]
I've closed https://github.com/Samsung/islet-asset/pull/7, it's unneeded now as all its changes has been pushed to a new branch (tf-a-rss).

**Comment by bitboom** [comment]
> > I made a PR and checked CI. _(HES build test on CI too)_ #200.
> 
> > If you agree with this PR, please merge it to this PR.
> 
> 
> 
> Done. I've amended one little cosmetic (duplicated DEBUG param for TF-A). Tested and looks good to me. I've rebased again on latest main and pushed. Should I squash those commits a little (e.g. to get rid of submodule changes in third-party/tf-a)? Or do we leave it as it is?


It's okay to leave them. Feel free to merge this PR to main. Thanks for contributing HES 👍

**Pull request merged**
