### PR TITLE
sdk: Replace .so file

### PR DESCRIPTION
**Pull request by zpzigi754**
This PR sidesteps the issue https://github.com/Samsung/islet/issues/159 to avoid a build error.

### CODE REVIEW

**Comment by bitboom** [comment]
Could you please change `cdylib` to `staticlib` & `.so` to `.a`?

**Comment by zpzigi754** [comment]
> Could you please change `cdylib` to `staticlib` & `.so` to `.a`?

Thank you for the suggestion.
`make run-simulated-c` doesn't seem to run with the static library (.a file) because of linking failure.

```
$ make run-simulated-c
    Finished release [optimized] target(s) in 0.05s
/usr/bin/ld: /home/changho/zpzigi754/islet/out/x86_64-unknown-linux-gnu/release/libislet_sdk.a(std-62c4894b82797b30.std.caeb81ab-cgu.0.rcgu.o): in function `std::sys::unix::thread::guard::get_stack_start':
/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/sys/unix/thread.rs:717: undefined reference to `pthread_getattr_np'
/usr/bin/ld: /rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/sys/unix/thread.rs:721: undefined reference to `pthread_attr_getstack'
/usr/bin/ld: /home/changho/zpzigi754/islet/out/x86_64-unknown-linux-gnu/release/libislet_sdk.a(std-62c4894b82797b30.std.caeb81ab-cgu.0.rcgu.o): in function `std::sys::unix::thread_local_key::get':
/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/sys/unix/thread_local_key.rs:22: undefined reference to `pthread_getspecific'
/usr/bin/ld: /home/changho/zpzigi754/islet/out/x86_64-unknown-linux-gnu/release/libislet_sdk.a(std-62c4894b82797b30.std.caeb81ab-cgu.0.rcgu.o): in function `std::sys::unix::thread_local_key::set':
/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/sys/unix/thread_local_key.rs:16: undefined reference to `pthread_setspecific'
...
```

**Comment by bitboom** [comment]
> To use the suggested static linking, I guess that the library which rust's standard library depends on also manually needs to be linked somehow?

When I tried it, it succeed..
## diff
```
 [lib]
-crate-type = ["rlib", "cdylib"]
+crate-type = ["rlib", "staticlib"]

 [build-dependencies]
 cbindgen = "0.24.0"
diff --git a/sdk/Makefile b/sdk/Makefile
index ffe645bc6c82..d967e962faa7 100644
--- a/sdk/Makefile
+++ b/sdk/Makefile
@@ -43,7 +43,7 @@ fvp: sdk sdk-example
        @mkdir -p $(SHARED_DIR)
        @install -m755 $(ROOT)/out/aarch64-unknown-linux-gnu/release/examples/aarch64 $(SHARED_DIR)/sdk-example
        @$(MAKE) sdk-example-c
-       @cp -p $(ROOT)/out/aarch64-unknown-linux-gnu/release/libislet_sdk.so  $(SHARED_DIR)
+       @cp -p $(ROOT)/out/aarch64-unknown-linux-gnu/release/libislet_sdk.a  $(SHARED_DIR)
        @install -m755 sdk-example-c $(SHARED_DIR)
```

## result
```
 make run-simulated-c
   Compiling islet_sdk v0.1.0 (/home/sangwan/islet/sdk)
    Finished release [optimized] target(s) in 0.73s
Simulated attestation operation on x86_64.
Verify Realm Signature.
== Signature Verification:
Sign Algo        = [ES384]
Public Key       = ["0476f988091be585ed41801aecfab858548c63057e16b0e676120bbd0d2f9c29e056c5d41a0130eb9c21517899dc23146b28e1b062bd3ea4b315fd219f1cbb528cb6e74ca49be16773734f61a1ca61031b2bbf3d918f2f94ffc4228e50919544ae"]
Data             = ["846a5369676e61747572653144a1013822405901b6a70a5840abababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababab19accb58400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000019accd58610476f988091be585ed41801aecfab858548c63057e16b0e676120bbd0d2f9c29e056c5d41a0130eb9c21517899dc23146b28e1b062bd3ea4b315fd219f1cbb528cb6e74ca49be16773734f61a1ca61031b2bbf3d918f2f94ffc4228e50919544ae19accc677368612d32353619acd0677368612d32353619acce58206190eb90b293886c172ec644dafb7e33ee2cea6541abe15300d96380df525bf919accf8458200000000000000000000000000000000000000000000000000000000000000000582000000000000000000000000000000000000000000000000000000000000000005820000000000000000000000000000000000000000000000000000000000000000058200000000000000000000000000000000000000000000000000000000000000000"]
Signature        = ["ec4f3b28a00feabd1f58f94acb27fdc7957545409f1c9f5d855793301a55baf4d4b4305728b4a4af95302013dad3628270b30a797a8c86d29ee6aeed11d33f930f367a22143053bf25f4368f389000a4ddfe065ad6ca9a37efcb8b3cdecd9cf3"]
== End of Signature Verification
```

I used ubuntu 22.04.
Are there differences between our env..?

**Comment by zpzigi754** [comment]
> When I tried it, it succeed.. 
...
> I used ubuntu 22.04. Are there differences between our env..?

Thank you for the trial. I've confirmed that the suggestion doesn't affect fvp-cca script usage in my environment and reflected your suggestion (I wonder why my environment fails to run `make simulated-run-c`).

**Review by bitboom — APPROVED** [review]

**Pull request merged**
