### PR TITLE
Rsi set ripas

### PR DESCRIPTION
**Pull request by bokdeuk-jeong**
1. update rsi event handler parameter
2. Record requests with RSI_IPA_STATE_SET and its results from RTT_INIT_RIPAS in Rec struct.
3. Move handlers in rec/mod.rs to rec/handlers.rs

### CODE REVIEW

**Comment by zpzigi754** [comment]
Is there any reason to move `Rec` from `rec/mod.rs` to `rec/rec.rs`?
Maintaining the same name for the folder and the file might not be desirable in terms of duplication and hierarchy.

BTW, moving the rec directory to a higher location might be desirable (current: `monitor/src/rmi/rec/` suggestion: `monitor/src/rec/`), as rec is a common data structure accessed by multiple entities (e.g., `rmi`, `rsi`).

**Comment by bokdeuk-jeong** [comment]
> Is there any reason to move `Rec` from `rec/mod.rs` to `rec/rec.rs`? Maintaining the same name for the folder and the file might not be desirable in terms of duplication and hierarchy.
> 
> BTW, moving the rec directory to a higher location might be desirable (current: `monitor/src/rmi/rec/` suggestion: `monitor/src/rec/`), as rec is a common data structure accessed by multiple entities (e.g., `rmi`, `rsi`).

Existing rec/mod.rs contains both struct Rec and event handlers for RMI_REC_OOOO requests.  It is expected that both struct Rec and handlers will be much bigger when we complete the implementation. So I thought that it would be more readable if they are splitted into different source files. 

Moving struct Rec out of rmi sounds reasonable.

**Comment by zpzigi754** [comment]
> Existing rec/mod.rs contains both struct Rec and event handlers for RMI_REC_OOOO requests. It is expected that both struct Rec and handlers will be much bigger when we complete the implementation. So I thought that it would be more readable if they are splitted into different source files.

I agree with the intention of the split. How about moving the handlers into another file like `handlers.rs`? Then, it would be able to avoid creating the same name of file and directory.

**Comment by bokdeuk-jeong** [comment]
> > Existing rec/mod.rs contains both struct Rec and event handlers for RMI_REC_OOOO requests. It is expected that both struct Rec and handlers will be much bigger when we complete the implementation. So I thought that it would be more readable if they are splitted into different source files.
> 
> I agree with the intention of the split. How about moving the handlers into another file like `handlers.rs`? Then, it would be able to avoid creating the same name of file and directory.

I think you opened up a good agenda to discuss. struct Rd and struct Rec are used by both rmi and rsi. 
However, I will move event handlers to handlers.rs and take struct Rec back to mod.rs for now. Thanks!

**Comment by bokdeuk-jeong** [comment]
last commit ammend is not applied to PR. I will close this and open another.

**Pull request closed without merging**
